services:
  neo4j:
    image: "neo4j:5.20.0-community-bullseye"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
volumes:
  neo4j_data:
  neo4j_logs:
